
## Condor Settings
universe = vanilla
transfer_executable = true
priority = 1000
request_memory = 512m

## Get input filename from command line
infile = thisisgoingtofail
infilefullpath = $Ff(infile)
identifier = $Fn(infile)

## Our Job
executable = run_larsoft.sh
output = $(identifier).stdout
error = $(identifier).stderr
log = $(identifier).condorlog
env = "ClusterId=$(ClusterId) ProcId=$(ProcId)"
arguments = $(infilefullpath) $(identifier)

## Queue the Job
queue
